Feat/pf 108
okode/nx-okode pull request #27
Opened 2023-04-20 06:24 UTC by arenas-okode

2023-04-20 12:53 UTC, rpanadero requested changes

2023-04-20 12:53 UTC, rpanadero commented on packages/angular/src/generators/setup-ssr/generator.ts
> +  appFunction.insertStatements(1, [`server.disable('x-powered-by');`]);
No hace exactamente lo mismo. Antes metía la instrucción después de la definición de la variable `server`. ¿Se podría, @arenas-okode ?

2023-04-20 14:30 UTC, arenas-okode commented on packages/angular/src/generators/setup-ssr/generator.ts
> +  appFunction.insertStatements(1, [`server.disable('x-powered-by');`]);
La funcion `appFunction.insertStatements(1, ['server.disable('x-powered-by');']); ` hace una inserción en la posición 1 de la función, en la posición 0 se encuentra la definición de server. 
El resultado de las pruebas e2e al ejecutar este generador es este:
```
export function app(): express.Express {
  const server = express();
  server.use(compression());
  server.use(requestContext);
  server.use(responseLogger);
  server.disable('x-powered-by');
```

2023-04-21 12:33 UTC, rpanadero commented on packages/angular/src/generators/setup-ssr/generator.ts
> +  appFunction.insertStatements(1, [`server.disable('x-powered-by');`]);
Pregunta a David sobre esto.

2023-04-25 15:42 UTC, rpanadero commented
@arenas-okode , recuerda corregir el conflicto.

2023-04-27 07:43 UTC, merged